version: '3.8'

services:
  postgres:
    image: ankane/pgvector:latest
    container_name: fraud-db
    networks:
      - fraud-net
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: fraud_db
    volumes:
      - pgdata:/var/lib/postgresql/data

  rag-api:
    build: .
    ports:
      - "8001:8000"
    networks:
      - fraud-net
    environment:
      - DATABASE_URL=postgresql://user:password@postgres:5432/fraud_db
      - HF_HOME=/app/model_cache
      - APP_ENV=prod
    volumes:
      - ./model_cache:/app/model_cache
    depends_on:
      - postgres
    command: > 
      uvicorn services.api.main:app --host 0.0.0.0 --port 8000 --log-level debug

  kafka-consumer:
    build: .
    command: python services/consumer/consumer.py
    networks:
      - fraud-net
    environment:
      APP_ENV: prod
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
    depends_on:
      - postgres

  embedder-worker:
    build: .
    command: python services/embedder/worker.py
    networks:
      - fraud-net
    environment:
      - APP_ENV=prod
      - HF_HOME=/app/model_cache
    volumes:
      - ./model_cache:/app/model_cache
    depends_on:
      - postgres

#  ollama:
#    image: ollama/ollama:latest
#    container_name: ollama
#    ports:
#      - "11434:11434"
#    volumes:
#      - ollama_data:/root/.ollama
#    networks:
#      - fraud-net

volumes:
  pgdata:
  ollama_data:

networks:
  fraud-net:
    external: true