version: '3.8'

services:
  postgres:
    image: ankane/pgvector:latest
    container_name: fraud-db
    networks:
      - fraud-net
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: fraud_db
    volumes:
      - pgdata:/var/lib/postgresql/data

  rag-api:
    build: .
    ports:
      - "8002:8000"
    networks:
      - fraud-net
    environment:
      - DATABASE_URL=postgresql://user:password@postgres:5432/fraud_db
      - HF_HOME=/app/model_cache
      - APP_ENV=prod
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./model_cache:/app/model_cache
    depends_on:
      - postgres
    command: > 
      uvicorn services.api.main:app --host 0.0.0.0 --port 8000 --log-level debug

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - fraud-net
    entrypoint: >
      sh -c "
        ollama serve &
        sleep 3 &&
        ollama pull llama3 &&
        wait
      "

  transaction-dashboard:
    image: python:3.12-slim
    container_name: transaction-monitor
    ports:
      - "8501:8501"
    environment:
      - APP_ENV=prod
    volumes:
      - ./services/streamlit:/app/services/streamlit
      - ./config:/app/config
      - ./shared:/app/shared
    working_dir: /app
    command: >
      bash -c "
        pip install --no-cache-dir streamlit>=1.38.0 requests>=2.31.0 pandas>=2.2.0 confluent-kafka>=2.3.0 docker>=7.1.0 pyyaml>=6.0 pydantic>=2.5.0 &&
        export PYTHONPATH=/app:/app/services/streamlit:/app/config:/app/shared &&
        streamlit run services/streamlit/app.py --server.port=8501 --server.address=0.0.0.0 --server.enableCORS=false --server.enableXsrfProtection=false
      "
#    restart: unless-stopped
    networks:
      - fraud-net

volumes:
  pgdata:
  ollama_data:

networks:
  fraud-net:
    external: true