"""initial_fraud_schema

Revision ID: a991223705af
Revises: 
Create Date: 2026-02-14 17:35:36.473785

"""
import datetime
from typing import Sequence, Union

from pgvector.sqlalchemy import Vector

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a991223705af'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
    sa.Column('transaction_id', sa.UUID(), nullable=False),
    sa.Column('event_time_seconds', sa.INTEGER(), nullable=False),
    sa.Column('event_timestamp', sa.TIMESTAMP(), nullable=False),
    sa.Column('amount', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('is_fraud', sa.BOOLEAN(), nullable=False),
    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('data_source', sa.VARCHAR(length=50), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False, default=datetime.datetime.now()),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    op.create_table('transaction_embeddings',
    sa.Column('transaction_id', sa.UUID(), nullable=False),
    sa.Column('embedding', Vector(384), nullable=False),
    sa.Column('embedding_text', sa.TEXT(), nullable=False),
    sa.Column('embedding_model', sa.VARCHAR(length=100), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False, default=datetime.datetime.now()),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.transaction_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction_embeddings')
    op.drop_table('transactions')
    # ### end Alembic commands ###
