database:
  url: "postgresql://user:password@postgres:5432/fraud_db"
  batch_size: 50

kafka:
  bootstrap_servers: "kafka:29092"
  topic: "transaction-decisions"
  group_id: "fraud-rag-group"

embedding:
  model_name: "all-MiniLM-L6-v2"
  dimension: 384

#llm:
#  provider: "openai"
#  base_url: "https://api.openai.com/v1"
#  api_key: "${OPENAI_API_KEY}"
#  model_name: "gpt-4o"

llm:
  provider: "ollama"
  base_url: "http://ollama:11434/v1"
  api_key: "ollama"
  model_name: "llama3"

dashboard:
  rag_url: "http://rag-api:8000/ask"
  inject_url: "http://fraud-detection-service:8000/transaction/inject?duration_seconds=1"

correlation_analysis:
  features:
    V17: -0.326481
    V14: -0.302544
    V12: -0.260593
    V10: -0.216883
    V16: -0.196539
    V3:  -0.192961
    V7:  -0.187257
    V11:  0.154876
    V4:   0.133447
    V18: -0.111485
    V1:  -0.101347
    V9:  -0.097733
    V5:  -0.094974
    V2:   0.091289
    V6:  -0.043643
    V21:  0.040413
    V19:  0.034783
    V20:  0.020090
    V8:   0.019875
    V27:  0.017580
    V28:  0.009536

  thresholds:
    critical_negative: -2.0
    critical_positive: 2.0
    high_impact_abs: 0.2